# Generated by Django 4.2.9 on 2024-02-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='username',
            name='login_data',
        ),
        migrations.AddField(
            model_name='username',
            name='email',
            field=models.CharField(default='test@test.ru', max_length=50),
        ),
        migrations.AddField(
            model_name='username',
            name='name',
            field=models.CharField(default='testuser', max_length=50),
        ),
    ]
